name: Install and build nestjs app

on:
  push:

env:
  PROJECT_ID: 'this is the projectId'

jobs:
  installing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo $PROJECT_ID
